手順7 モデルの単体テストコードを書く
 Failure/Error: expect(@item.errors.full_messages).to include("Price は¥9,999,999以下してください")
       expected ["Item category can't be blank", "Item description can't be blank", "Shipping fee can't be blank", "Prefecture can't be blank", "Shipping term can't be blank"] to include "Price は¥9,999,999以下してください"

==> 長いのでACTIVE HAS Hのところに関係のあるところを修正
今回の場合は１以上であればOK

=====

  1) Item 商品出品登録 商品出品がうまくいかないとき item_categoryが空では出品できない
     Failure/Error: expect(@item.errors.full_messages).to include("Item description can't be blank", "Shipping fee can't be blank", "Prefecture can't be blank", "Shipping term can't be blank")
       expected ["Item category can't be blank"] to include "Item description can't be blank", "Shipping fee can't be blank", "Prefecture can't be blank", and "Shipping term can't be blank"
     # ./spec/models/item_spec.rb:46:in `block (4 levels) in <top (required)>'

  2) Item 商品出品登録 商品出品がうまくいかないとき shipping_feeが空では出品できない
     Failure/Error: @item.shipping_fee = 1

     NoMethodError:
       undefined method `id' for 1:Integer
       Did you mean?  i