Memo
ActionController::ParameterMissing (param is missing or the value is empty: order_sender):

=====
NameError in OrdersController#create
undefined local variable or method `current_item' for #<OrdersController:0x00007fee6c017108> Did you mean? current_user @current_user