購入画面に進むために
rails routeをした時
toute.rbのorderになっていたから移行しなかった
また、ROOTINGエラーが起きていた

『参照エラー』
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    33:
    34:         <%# 商品が売れていない場合はこちらを表示しましょう ：次回実装のための覚書としてメモを残しています %>
    35:        <%else%>
    36:         <%= link_to "購入画面に進む", item_order_index_path(@order.id) ,class:"item-red-btn"%>　
    37:         <%# 上記のリンクを指定することSTEP１ %>
    38:         <%# //商品が売れていない場合はこちらを表示しましょう ：次回実装のための覚書としてメモを残しています %>
    39:

app/views/items/show.html.erb:36

＝＞メソッドが抜けていた

＝＝＝＝＝＝
ルーティングエラー
ーーーーー
Started GET "/items/16/order" for ::1 at 2023-05-11 21:29:09 +0900

ActionController::RoutingError (uninitialized constant OrderController
Did you mean?  OrdersController):

＝＝＝＝

ArgumentError (You need to supply at least one validation):

app/models/order_sender.rb:13:in `<class:OrderSender>'
app/models/order_sender.rb:1:in `<main>'
app/controllers/orders_controller.rb:12:in `index'

＝＝＞ORDER＿SEMDER.RBのばりでーしょんでしっかり書かれていないものがあったからエラーが起きていた